# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Project
archives_base_name=fidgetz
maven_group=io.github.fishstiz.fidgetz
mod_version=0.5.0-beta.3+26.1
mod_id=fidgetz
mod_name=fidgetz
mod_author=fishstiz
mod_description=fishstiz widgets for Minecraft GUIs
credits=
license=MIT
sources=https://github.com/fishstiz/fidgetz
issues=https://github.com/fishstiz/fidgetz/issues
java_version=25

# Common
minecraft_version=26.1
moddev_version=2.0.140
neo_form_version=26.1-1
mixin_version=0.8.7
mixinextras_version=0.5.0
mod_publish_version=1.1.0

# Fabric
loom_version=1.16-SNAPSHOT
fabric_loader_version=0.18.4
fabric_api_version=0.143.15+26.1
fabric_minecraft_version_range=~26.1

# NeoForge
neoforge_version=26.1.2.36-beta
neoforge_loader_version_range=[4,)
neoforge_version_range=[26.1.0.0-alpha.0,)
neoforge_minecraft_version_range=[26.1-rc-1,26.2)
