plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
}

loader {
    commonPath = ':testmod:common'
}

dependencies {
    minecraft "com.mojang:minecraft:$minecraft_version"
    implementation "net.fabricmc:fabric-loader:$fabric_loader_version"
    implementation "net.fabricmc.fabric-api:fabric-api:$fabric_api_version"

    implementation project(":fabric")
}

loom {
    def aw = file("src/main/resources/testmod.classtweaker")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }

    mods {
        testmod {
            sourceSet sourceSets.main
        }
    }

    runs {
        remove server

        client {
            client()
            getDisplayName().set('Fabric Client Test')
            getGenerateRunConfig().set(true)
            getRunDirectory().set(new File('run/testmod'))
            getJvmArguments().add('-Dfidgetz.debug')
        }
    }
}
