import me.modmuss50.mpp.ReleaseType

plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id 'publish-local'
    id 'me.modmuss50.mod-publish-plugin'
}

dependencies {
    minecraft "com.mojang:minecraft:$minecraft_version"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${minecraft_version}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:$fabric_loader_version"
    modImplementation "net.fabricmc.fabric-api:fabric-api:$fabric_api_version"
}

loom {
    def aw = file("src/main/resources/${mod_id}.classtweaker")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }

    runs {
        remove client
        remove server
    }
}

publishMods {
    dryRun = Boolean.valueOf(dry_run)
    type = ReleaseType.of(release_type)
    changelog = rootProject.file("CHANGELOG.md").text
    file = remapJar.archiveFile
    additionalFiles.from(remapSourcesJar.archiveFile)
    displayName = "Fabric v${this.version}"
    modLoaders.add("neoforge")

    github {
        parent rootProject.tasks.named("publishGithub")
        accessToken = findProperty("GITHUB_TOKEN") ?: ""
    }
}
