import me.modmuss50.mpp.ReleaseType

plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'publish-local'
    id 'me.modmuss50.mod-publish-plugin'
}

neoForge {
    version = neoforge_version

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }

    parchment {
        minecraftVersion = minecraft_version
        mappingsVersion = parchment_version
    }
}

publishMods {
    dryRun = Boolean.valueOf(dry_run)
    type = ReleaseType.of(release_type)
    changelog = rootProject.file("CHANGELOG.md").text
    file = jar.archiveFile
    additionalFiles.from(sourcesJar.archiveFile)
    displayName = "NeoForge v${this.version}"
    modLoaders.add("neoforge")

    github {
        parent rootProject.tasks.named("publishGithub")
        accessToken = findProperty("GITHUB_TOKEN") ?: ""
    }
}